[tool.poetry]
name = "ragpractice"
version = "0.1.0"
description = ""
authors = ["Noah Jaffe <noah.h.jaffe@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
pdfminer = "^20191125"
pdfminer-six = "^20231228"
langchain = "^0.1.19"
unstructured = {extras = ["md"], version = "^0.13.7"}
openai = "^1.28.0"
chromadb = "^0.5.0"
tiktoken = "^0.6.0"
langchain-openai = "^0.1.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
